notely/notely/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("notes.urls"))
]

notely/notes/urls.py
from . import views 
from django.urls import path 

app_name = "notes"

urlpatterns = [
    path("", views.index, name="index"),
    path("register", views.register, name="register"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("create", views.create, name="create"),
    path("note", views.note, name="note"),
    path("note/<str:category>", views.category, name="category"),
    path("note/<str:category>/<str:title>", views.content, name="content"),
    path("edit/<str:category>/<str:title>", views.edit, name="edit"),
    path("delete/<str:category>/<str:title>", views.delete, name="delete")
]

notely/notes/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    
    email = models.EmailField(unique=True, null=False, blank=False)
    
    def __str__(self):
        return f"{self.username}"
    
# For notes
class Note(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notes")
    category = models.CharField(max_length=64)
    title = models.CharField(max_length=64)
    content = models.TextField()

notely/notes/views.py
from django.shortcuts import render
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate, decorators
from django.http import HttpResponseRedirect
from django.urls import reverse
import markdown

from django import forms
from .models import User, Note

import re
from validate_email import validate_email

PASSWORD_REGEX = r"^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[\$\*\#@])[A-Za-z\d\$\*\#@]{5,8}$"
USERNAME_REGEX = r"^[a-zA-Z][a-zA-Z0-9]{4,7}$"

# Form for registering
class RegisterForm(forms.Form):
    username = forms.CharField(max_length=64, label="Username", widget=forms.TextInput(attrs={
        "placeholder" : "Eg. John Doe",
        "autocomplete" : "off"
    }))
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={
        "placeholder" : "johndoe@gmail.com",
        "autocomplete" : "off"
    }))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={
        "placeholder" : "*****",
        "autocomplete" : "off"
    }))
    confirmPassword = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={
        "placeholder" : "*****",
        "autocomplete" : "off"
    }))
    
    # For validination username
    def clean_username(self):
        username = self.cleaned_data.get("username")
        
        if not re.match(USERNAME_REGEX, username):
            raise forms.ValidationError("Username must start with a letter and be 5 to 8 characters long. Only letters and numbers are allowed.")

        return username 
    
    # For validation email
    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not validate_email(email):
            raise forms.ValidationError("Invalid Email")
        
        return email 
    
    # For validation password
    def clean_password(self):
        password = self.cleaned_data.get("password")
        if not re.match(PASSWORD_REGEX, password):
            raise forms.ValidationError("Password must be 5–8 characters long, contain at least 1 uppercase letter, 1 lowercase letter, 1 number, and 1 special character ($ * # @).")
        
        return password 
    
    # For validtion confirmPassword
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirmPassword")

        if password and confirm_password and password != confirm_password:
            self.add_error("confirmPassword", "Passwords must match")


# For for loggin in
class LoginForm(forms.Form):
    username = forms.CharField(label="Email", widget=forms.TextInput(attrs={
        "placeholder" : "jhondoe",
        "autocomplete" : "off"
    }))
    
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={
        "placeholder" : "*****",
        "autocomplete" : "off"
    }))
    
    # for validing email
    def clean_username(self):
        username = self.cleaned_data.get("username")
        
        if not re.match(USERNAME_REGEX, username):
            raise forms.ValidationError("Username must start with a letter and be 5 to 8 characters long. Only letters and numbers are allowed")

        return username 
    
    # for valding password
    def clean_password(self):
        password = self.cleaned_data.get("password")
        if not re.match(PASSWORD_REGEX, password):
            raise forms.ValidationError("Password must be 5–8 characters long, contain at least 1 uppercase letter, 1 lowercase letter, 1 number, and 1 special character ($ * # @).")

        return password
    
    
# for creating note
class NoteForm(forms.Form):
       title = forms.CharField(label="Title", widget=forms.TextInput(attrs={
           "placeholder" : "State",
           "autocomplete" : "off"
       })) 
       category = forms.CharField(label="Category", widget=forms.TextInput(attrs={
           "placeholder" : "React",
           "autocomplete" : "off"
       }))
       content = forms.CharField(label="Content", widget=forms.Textarea(attrs={
           "placeholder" : "React is a js library",
           "autocomplete" : "off"
       }))
    
# Create your views here.
# Main Page
def index(request):
    return render(request, "notes/index.html")

# For Registering
def register(request):
    
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("notes:index"))
    
    if request.method == "GET":
        return render(request, "notes/register.html",{
            "form" : RegisterForm()
        })
    
    # For post method
    form = RegisterForm(request.POST)
    
    if (form.is_valid()):
        
        # Get data
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        confirmPassword = form.cleaned_data.get("confirmPassword")
        
        # try to create a new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "notes/register.html", {
                "form" : form,
                "message" : "Email or username already exists"
            })
        
        # logging the user in
        login(request, user)
        
        # Redirect to home page
        return HttpResponseRedirect(reverse("notes:index"))
    
    return render(request, "notes/register.html", {
        "form" : form
    })
    
# For Logging in
def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("notes:index"))
    
    if request.method == "GET":
        return render(request, "notes/login.html", {
            "form" : LoginForm()
        })
    
    # for post method
    form = LoginForm(request.POST)
    
    if form.is_valid():
        # Getting username and password
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        
        user = authenticate(request, username=username, password=password)
        
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse("notes:index"))
        
        return render(request, "notes/login.html", {
            "form" : form,
            "message" : "Invalid Username of password"
        })
         
    return render(request, "notes/login.html", {
        "form" : form
    })

# for loggin out
\
def logout_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("notes:login"))
    logout(request)
    return HttpResponseRedirect(reverse("notes:register"))


# For Creating note
def create(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("notes:login"))
    if request.method == "GET":
        return render(request, "notes/create.html", {
            "form" : NoteForm()
        })
        
    # for get method
    form = NoteForm(request.POST)
    
    if form.is_valid():
        category = form.cleaned_data.get("category")
        title = form.cleaned_data.get("title")
        content = form.cleaned_data.get("content")
        
        note = Note(owner=request.user, category=category, title=title, content=content)
        note.save()
        
        return HttpResponseRedirect(reverse("notes:note"))
    
    return render(request, "notes/create.html", {
        "form" : form
    })


# For viewsing category
def note(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("notes:login"))
    # Getting all the category of user
    categories = Note.objects.filter(owner=request.user).values_list("category", flat=True).distinct()
    
    return render(request, "notes/category.html", {
        "categories" : list(categories)
    })
    
# for viewing actual title

def category(request, category):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("notes:login"))
    noteLists = Note.objects.filter(owner=request.user, category=category)
    
    if not noteLists:
        return HttpResponseRedirect(reverse("notes:note"))
    
    return render(request, "notes/notes.html", {
        "notes" : noteLists,
        "category" : category
    })

# for viewing content of the note

def content(request, category, title):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("notes:login"))
    note = Note.objects.filter(owner=request.user, category=category, title=title).first()
    
    if not note:
        return HttpResponseRedirect(reverse("notes:note"))
    
    return render(request, "notes/content.html", {
        "note" : note,
        "content" : markdown.markdown(note.content)
    })
    
# For editing

def edit(request, category, title):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("notes:login"))
    if request.method == "GET":
        note = Note.objects.filter(owner=request.user, category=category, title=title).first()
        
        if not note:
            return HttpResponseRedirect(reverse("notes:note"))
        
        return render(request, "notes/edit.html", {
            "note" : note
        })
    
    # for post method
    form = NoteForm(request.POST)
    
    if form.is_valid():
        content = form.cleaned_data.get("content")
        note = Note.objects.filter(owner=request.user, category=category,title=title).first()
        note.content = content
        note.save()
        return HttpResponseRedirect(reverse("notes:content", args=[category, title]))


# for deletiong

def delete(request, category, title):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("notes:login"))
    
    note = Note.objects.filter(owner=request.user, category=category, title=title).first()
    
    if not note:

notely/notes/templates/notes/category.html
{% extends "notes/layout.html" %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'notes/css/category.css' %}">
{% endblock %}
{% block title %}
    Notes
{% endblock %}

{% block body %}
    <h2>Your Note Categories</h2>
    <input type="search" name="q" id="q" placeholder="Search Query">
    <ul class="category-list">
        {% for category in categories %}
            <li><a class="category" href="{% url 'notes:category' category %}">{{category}}</a></li>
        {% empty %}
            <li class="warning">You don't have any note currently.Add some <a href="{% url 'notes:create' %}">Here</a></li>
        {% endfor %}
    </ul>

    <script src="{% static 'notes/js/category.js' %}"></script>
{% endblock %}

notely/notes/templates/notes/content.html
{% extends "notes/layout.html" %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'notes/css/content.css' %}">
{% endblock %}

{% block title %}
    {{note.title}}
{% endblock %}

{% block body %}
    <div class="content">
        {{content|safe}}
        <a href="{% url 'notes:edit' note.category note.title %}" class="edit btn">Edit</a>
        <a href="{% url 'notes:delete'  note.category note.title %}" class="delete btn">Delete</a>
    </div>
{% endblock %}

notely/notes/templates/notes/create.html
{% extends "notes/layout.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'notes/css/create.css' %}">
{% endblock %}
{% block title %}
    Create
{% endblock %}

{% block body %}
    <div class="create">
        <h1>Create Note</h1>
        <form action="{% url 'notes:create' %}" method="POST" class="create-form">
            {% csrf_token %}
            <div class="category">
                {{form.category.label_tag}}
                {{form.category}}
                {% for error in form.category.errors %}
                    <span>{{error}}</span>
                {% endfor %}
            </div>

            <div class="title">
                {{form.title.label_tag}}
                {{form.title}}
                {% for error in form.title.errors %}
                    <span>{{error}}</span>
                {% endfor %}
            </div>

            <div class="content">
                {{form.content.label_tag}}
                {{form.content}}
                {% for error in form.content.errors %}
                    <span>{{error}}</span>
                {% endfor %}
            </div>
            <button type="submit">Create</button>
        </form>
    </div>
    <script src="{% static 'notes/js/create.js' %}"></script>
{% endblock %}

notely/notes/templates/notes/edit.html
{% extends "notes/layout.html" %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'notes/css/create.css' %}">
{% endblock %}
{% block title %}
    Edit {{note.title}}
{% endblock %}

{% block body %}
    <div class="create">
        <h2>Edit {{note.title}}</h2>
        <form action="{% url 'notes:edit' note.category note.title %}" method="POST" class="create-form">
            {% csrf_token %}
            <div class="category">
                <label for="category">Category</label>
                <input type="text" name="category" id="category" readonly value={{note.category}}>
            </div>
            <div class="title">
                <label for="title">Title</label>
                <input type="text" name="title" id="title" readonly value={{note.title}}>
            </div>
            <div class="content">
                <label for="content">Content</label>
                <textarea name="content" id="content" rows="6">{{note.content}}</textarea>
            </div>
            <button type="submit">Save</button>
        </form>
    </div>
{% endblock %}

notely/notes/templates/notes/index.html
{% extends "notes/layout.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "notes/css/index.css" %}">
{% endblock %}

{% block title %}
    Notely
{% endblock %}

{% block body %}
    <div id="particles-js">
        <div class="hero-section">
            <h1>Your Notes, Anywhere, Anytime</h1>
            <p>
                Experience the freedom of accessing your notes from any device, with the assurance of complete privacy and a 
                user-friendly interface.
            </p>
            <a href="{% url 'notes:create' %}">Create Note</a>
        </div>
    </div>

    <div class="adding">
        <h2>Adding Notes</h2>
        <p>Adding notes is simple and intuitive. Follow these steps to get started.</p>

        <div class="steps">
            <div class="create">
                <img src="{% static 'notes/assets/one.jpg' %}" alt="create"/>
                <h3>Create Note</h3>
                <p>Click <span>Create</span> to create a new note. Start writing immediately with our easy-to-use editor.</p>
            </div>
            <div class="organize">
                <img src="{% static 'notes/assets/two.jpg' %}" alt="organize" />
                <h3>Organize Notes</h3>
                <p>
                    Add <span>Category</span> to keep your notes organized and easily searchable.
                </p>
            </div>
            <div class="access">
                <img src="{% static 'notes/assets/three.jpg' %}" alt="access">
                <h3>Access Anywhere</h3>
                <p>
                    Your notes are synced across all your devices, so you can access them anytime, anywhere.
                </p>
            </div>
        </div>
    </div>
    <div class="usage-info">
        <h2>✨ Elevate Your Notes with Markdown</h2>
        <p>
            Your words deserve more than plain text.
            <strong>Bold your thoughts</strong>,<em>italicize your ideas</em>,
            structure with headers, lists, and even embed code — 
            all with the magic of <span>GitHub-flavored Markdown</span>.
        </p>
        <p>It's powerful, it's simple nad it's made just for you.</p>
        <a href="https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax" target="_blank">Learn Markdown</a>
    </div>
    <script src="{% static 'notes/js/particles.js' %}"></script>
    <script src="{% static 'notes/js/app.js' %}"></script>
    <script src="{% static 'notes/js/index.js' %}"></script>
{% endblock %}

notely/notes/templates/notes/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'notes/css/layout.css' %}">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    {% block css %}

    {% endblock %}
</head>
<body>
    <header>
        <div class="banner">
            <i class="fa-solid fa-note-sticky"></i>
            <h1>Notely</h1>
        </div>

        <div class="menu-container">
            <nav class="navigation">
                <ul>
                    <li><a href="{% url 'notes:index' %}">Home</a></li>
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'notes:create' %}">Create</a></li>
                        <li><a href="{% url 'notes:note' %}">Your Notes</a></li>
                    {% endif %}
                </ul>
            </nav>

            <nav class="authentication-bar">
                <ul>
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'notes:logout' %}">Logout</a></li>
                        <li>{{request.user.username}}</li>
                    {% else %}
                        <li><a href="{% url 'notes:register' %}">Register</a></li>
                        <li><a href="{% url 'notes:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        
        <div class="menu-bar">
            <i class="fa-solid fa-bars"></i>
        </div>
    </header>
    {% block body %}

    {% endblock %}
    <script src="https://kit.fontawesome.com/a7a306d694.js" crossorigin="anonymous"></script>
    <script src="{% static 'notes/js/layout.js' %}"></script>
</body>
</html>

notely/notes/templates/notes/login.html
{% extends "notes/layout.html" %}


{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'notes/css/register.css' %}">
{% endblock %}

{% block title %}
    Login 
{% endblock %}

{% block body %}
    <div class="register">
        <h1>Login</h1>
        <form action="{% url 'notes:login' %}" method="POST" class="register-form">
            {% csrf_token %}
            <div clas="username">
                {{form.username.label_tag}}
                {{form.username}}
                {% for error in form.username.errors %}
                    <span>{{error}}</span>
                {% endfor %}
            </div>

            <div class="password">
                {{form.password.label_tag}}
                {{form.password}}
                {% for error in form.password.errors %}
                    <span>{{error}}</span>
                {% endfor %}
            </div>
            <button type="submit">Login</button>
        </form>
        {% if message %}
            <p class="warning">{{message}}</p>
        {% endif %}
        <p class="info">
            Don't have an account? Register <a href="{% url 'notes:register' %}">Here</a>
        </p>
    </div>
    <script src="{% static 'notes/js/login.js' %}"></script>
{% endblock %}

notely/notes/templates/notes/notes.html
{% extends "notes/layout.html" %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'notes/css/category.css' %}">
{% endblock %}
{% block title %}
    Notes
{% endblock %}

{% block body %}
    <h2>Your Notes for <span>{{category}}</span></h2>
    <input type="search" name="q" id="q" placeholder="Search Query">
    <ul class="category-list">
        {% for note in notes %}
            <li><a class="note" href="{% url 'notes:content' category note.title %}">{{note.title}}</a></li>
        {% endfor %}
    </ul>

    <script src="{% static 'notes/js/note.js' %}"></script>
{% endblock %}

notely/notes/templates/notes/register.html
{% extends "notes/layout.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'notes/css/register.css' %}">
{% endblock %}
{% block title %}
    Register
{% endblock %}

{% block body %}
    <div class="register">
        <h1>Register</h1>
        <form action="{% url 'notes:register' %}" method="POST" class="register-form">
            {% csrf_token %}
            <div class="username">
                {{form.username.label_tag}}
                {{form.username}}
                {% for error in form.username.errors %}
                    <span>{{error}}</span>
                {% endfor %}
            </div>

            <div class="email">
                {{form.email.label_tag}}
                {{form.email}}
                {% for error in form.email.errors %}
                    <span>{{error}}</span>
                {% endfor %}
            </div>

            <div class="password">
                {{form.password.label_tag}}
                {{form.password}}
                {% for error in form.password.errors %}
                    <span>{{error}}</span>
                {% endfor %}
            </div>

            <div class="confirmPassword">
                {{form.confirmPassword.label_tag}}
                {{form.confirmPassword}}
                {% for error in form.confirmPassword.errors %}
                    <span>{{error}}</span>
                {% endfor %}
            </div>
            <button type="submit">Register</button>
        </form>
        {% if message %}
            <p class="warning">{{message}}</p>
        {% endif %}
        <p class="info">
            Already have an account? Login <a href="{% url 'notes:login' %}">Here</a>
        </p>
    </div>
    <script src="{% static 'notes/js/register.js' %}"></script>
{% endblock %}